// Mock data for testing UI without backend

export const mockTestAssignments = {
  status: "success",
  data: {
    pending: [
      {
        assignment_id: 1,
        exam_id: 501,
        exam_title: "VSTEP Full Mock Test - De so 01",
        exam_type: "VSTEP",
        exam_skill: "reading",
        exam_format: "FULL_4_SKILLS",
        exam_duration: 179,
        total_questions: 80,
        max_score: 100,
        start_time: "2026-03-24 08:00:00",
        end_time: "2026-03-25 23:59:00",
        is_urgent: true,
        time_remaining: "23h 30m",
        attempts_allowed: 3,
        attempts_used: 0,
      },
      {
        assignment_id: 2,
        exam_id: 601,
        exam_title: "IELTS Academic Full Test - De A",
        exam_type: "IELTS",
        exam_skill: "reading",
        exam_format: "FULL_4_SKILLS",
        exam_duration: 165,
        total_questions: 75,
        max_score: 100,
        start_time: "2026-03-24 08:00:00",
        end_time: "2026-03-28 23:59:00",
        is_urgent: false,
        time_remaining: "4 ngày",
        attempts_allowed: 2,
        attempts_used: 0,
      },
      {
        assignment_id: 4,
        exam_id: 502,
        exam_title: "VSTEP Mini Mock - Rut gon 60 phut",
        exam_type: "VSTEP",
        exam_skill: "reading",
        exam_format: "MINI_MOCK",
        exam_duration: 60,
        total_questions: 36,
        max_score: 100,
        start_time: "2026-03-24 08:00:00",
        end_time: "2026-03-28 23:59:00",
        is_urgent: false,
        time_remaining: "4 ngày",
        attempts_allowed: 2,
        attempts_used: 0,
      },
    ],
    in_progress: [
      {
        assignment_id: 5,
        exam_id: 503,
        exam_title: "VSTEP Full Mock Test - De so 02",
        exam_type: "VSTEP",
        exam_skill: "reading",
        exam_format: "FULL_4_SKILLS",
        exam_duration: 179,
        total_questions: 80,
        max_score: 100,
        start_time: "2026-03-24 08:00:00",
        end_time: "2026-03-30 23:59:00",
        is_urgent: false,
        time_remaining: "6 ngày",
        attempts_allowed: 3,
        attempts_used: 1,
      },
    ],
    completed: [
      {
        assignment_id: 6,
        exam_id: 602,
        exam_title: "IELTS Academic Full Test - De B",
        exam_type: "IELTS",
        exam_skill: "reading",
        exam_format: "FULL_4_SKILLS",
        exam_duration: 165,
        total_questions: 75,
        max_score: 100,
        start_time: "2026-03-20 08:00:00",
        end_time: "2026-03-23 23:59:00",
        is_urgent: false,
        time_remaining: "0",
        attempts_allowed: 2,
        attempts_used: 1,
        submission_id: 1206,
      },
    ],
  },
};

export const mockSubmissions = {
  status: "success",
  data: {
    submissions: [
      {
        sId: 123,
        sScore: 82.5,
        sStatus: "graded",
        sSubmit_time: "2026-03-24 15:30:00",
        sGraded_time: "2026-03-24 15:35:00",
        sAttempt: 1,
        sTime_taken: 3263,
        exam: {
          eId: 5,
          eTitle: "IELTS Reading Practice",
          eType: "IELTS",
          eSkill: "reading",
          eTotal_questions: 40,
          eMax_score: 100,
        },
        stats: {
          correct_answers: 33,
          total_questions: 40,
          accuracy: 82.5,
          grade: "B+",
          rank_in_class: 5,
          total_students: 25,
        },
      },
    ],
  },
};

export const mockProgress = {
  status: "success",
  data: {
    overview: {
      total_tests: 24,
      average_score: 74.5,
      highest_score: 92.0,
      lowest_score: 58.0,
      recent_score: 82.5,
    },
    trends: {
      recent_scores: [
        { date: "2026-03-18", score: 70, exam_title: "Test 1", exam_type: "IELTS", exam_skill: "reading" },
        { date: "2026-03-19", score: 75, exam_title: "Test 2", exam_type: "IELTS", exam_skill: "reading" },
        { date: "2026-03-20", score: 78, exam_title: "Test 3", exam_type: "IELTS", exam_skill: "reading" },
        { date: "2026-03-21", score: 80, exam_title: "Test 4", exam_type: "IELTS", exam_skill: "reading" },
        { date: "2026-03-22", score: 82, exam_title: "Test 5", exam_type: "IELTS", exam_skill: "reading" },
        { date: "2026-03-23", score: 85, exam_title: "Test 6", exam_type: "IELTS", exam_skill: "reading" },
        { date: "2026-03-24", score: 82.5, exam_title: "Test 7", exam_type: "IELTS", exam_skill: "reading" },
      ],
    },
    skill_analysis: {
      skills_breakdown: [
        { skill: "reading", skill_name: "Đọc", count: 10, average_score: 78.5, highest_score: 92.0, lowest_score: 65.0, mastery_level: "advanced" },
        { skill: "listening", skill_name: "Nghe", count: 8, average_score: 72.0, highest_score: 85.0, lowest_score: 60.0, mastery_level: "intermediate" },
        { skill: "writing", skill_name: "Viết", count: 4, average_score: 68.0, highest_score: 75.0, lowest_score: 55.0, mastery_level: "intermediate" },
        { skill: "speaking", skill_name: "Nói", count: 2, average_score: 70.0, highest_score: 75.0, lowest_score: 65.0, mastery_level: "intermediate" },
      ],
    },
  },
};

export const mockPracticeTopics = {
  status: "success",
  data: {
    topics: [
      {
        id: 1,
        name: "Main Ideas & Details",
        skill: "reading",
        difficulty: "intermediate",
        total_questions: 150,
        completed_questions: 45,
        average_score: 78.5,
        estimated_time: "30 phút",
      },
      {
        id: 2,
        name: "Inference & Vocabulary",
        skill: "reading",
        difficulty: "hard",
        total_questions: 120,
        completed_questions: 20,
        average_score: 65.0,
        estimated_time: "25 phút",
      },
      {
        id: 3,
        name: "Conversation Practice",
        skill: "listening",
        difficulty: "easy",
        total_questions: 80,
        completed_questions: 60,
        average_score: 85.0,
        estimated_time: "20 phút",
      },
    ],
  },
};

export const mockNotifications = {
  status: "success",
  data: {
    notifications: [
      {
        id: 1,
        type: "assignment",
        title: "Bài tập mới được giao",
        message: "Giáo viên đã giao bài 'IELTS Reading Practice'",
        icon: "ClipboardList",
        color: "#2563EB",
        is_read: false,
        created_at: "2026-03-24 10:30:00",
        action_url: "/bai-tap/123",
        action_label: "Xem bài tập",
      },
      {
        id: 2,
        type: "graded",
        title: "Bài thi đã được chấm",
        message: "Bài 'VSTEP Reading' của bạn đã được chấm. Điểm: 85/100",
        icon: "CheckCircle",
        color: "#10B981",
        is_read: false,
        created_at: "2026-03-24 09:15:00",
        action_url: "/ket-qua/456",
        action_label: "Xem kết quả",
      },
    ],
    unread_count: 2,
  },
};
